package com.sysbusiness.users.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PK
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_NAME
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.DEPARTMENT_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.SUBJECT_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String subjectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_PASSWORD
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.STATUS
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.EMPLOYEE_ID
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.EMPLOYEE_TYPE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String employeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.MOBILE_TELEPHONE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String mobileTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.TELPHONE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.LOGIN_NAME
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ACCOUNT_STATUS
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.EMAIL
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ORDER_NO
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private Short orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.AGE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CARD_NO
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    private String cardNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PK
     *
     * @return the value of users.PK
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.PK
     *
     * @param pk the value for users.PK
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_CODE
     *
     * @return the value of users.USER_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER_CODE
     *
     * @param userCode the value for users.USER_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_NAME
     *
     * @return the value of users.USER_NAME
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER_NAME
     *
     * @param userName the value for users.USER_NAME
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.DEPARTMENT_CODE
     *
     * @return the value of users.DEPARTMENT_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.DEPARTMENT_CODE
     *
     * @param departmentCode the value for users.DEPARTMENT_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.SUBJECT_CODE
     *
     * @return the value of users.SUBJECT_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getSubjectCode() {
        return subjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.SUBJECT_CODE
     *
     * @param subjectCode the value for users.SUBJECT_CODE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_PASSWORD
     *
     * @return the value of users.USER_PASSWORD
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER_PASSWORD
     *
     * @param userPassword the value for users.USER_PASSWORD
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.STATUS
     *
     * @return the value of users.STATUS
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.STATUS
     *
     * @param status the value for users.STATUS
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.EMPLOYEE_ID
     *
     * @return the value of users.EMPLOYEE_ID
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.EMPLOYEE_ID
     *
     * @param employeeId the value for users.EMPLOYEE_ID
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.EMPLOYEE_TYPE
     *
     * @return the value of users.EMPLOYEE_TYPE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getEmployeeType() {
        return employeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.EMPLOYEE_TYPE
     *
     * @param employeeType the value for users.EMPLOYEE_TYPE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.MOBILE_TELEPHONE
     *
     * @return the value of users.MOBILE_TELEPHONE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getMobileTelephone() {
        return mobileTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.MOBILE_TELEPHONE
     *
     * @param mobileTelephone the value for users.MOBILE_TELEPHONE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setMobileTelephone(String mobileTelephone) {
        this.mobileTelephone = mobileTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.TELPHONE
     *
     * @return the value of users.TELPHONE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.TELPHONE
     *
     * @param telphone the value for users.TELPHONE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.LOGIN_NAME
     *
     * @return the value of users.LOGIN_NAME
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.LOGIN_NAME
     *
     * @param loginName the value for users.LOGIN_NAME
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ACCOUNT_STATUS
     *
     * @return the value of users.ACCOUNT_STATUS
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ACCOUNT_STATUS
     *
     * @param accountStatus the value for users.ACCOUNT_STATUS
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.EMAIL
     *
     * @return the value of users.EMAIL
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.EMAIL
     *
     * @param email the value for users.EMAIL
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ORDER_NO
     *
     * @return the value of users.ORDER_NO
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ORDER_NO
     *
     * @param orderNo the value for users.ORDER_NO
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.AGE
     *
     * @return the value of users.AGE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.AGE
     *
     * @param age the value for users.AGE
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CARD_NO
     *
     * @return the value of users.CARD_NO
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CARD_NO
     *
     * @param cardNo the value for users.CARD_NO
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
}