package com.sysbusiness.users.domain;

import com.sysbusiness.users.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    int deleteByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    User selectByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Thu Jul 14 16:45:11 CST 2016
     */
    int updateByPrimaryKey(User record);
}